apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This kustomization pulls in the manifests for the kube-prometheus operator stack.
# Download the manifests from the kube-prometheus release v0.16.0 into the corresponding directories.

resources:
  - ../manifests/setup
  - ../manifests
