apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- simplefin-secret.yaml
- simplefin-cronjob.yaml
- simplefin-servicemonitor.yaml
- simplefin-dashboard.yaml
- simplefin-rbac.yaml
- simplefin-recording-rules.yaml
- account-mappings-configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: homelab-monitoring